[env]
TERM = "alacritty"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[window]
dynamic_padding = true
option_as_alt = "Both"

[font]
size = 12

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[colors.primary]
background = '#1F1F1F'
foreground = '#D4D4D4'

[colors.cursor]
text = "#1F1F1F"
cursor = "#D4D4D4"

[colors.normal]
black = "#1F1F1F"
red = "#F44747"
green = "#6A9955"
yellow = "#DCDCAA"
blue = "#569CD6"
magenta = "#C678Dd"
cyan = "#56B6C2"
white = "#D4D4D4"

[colors.bright]
black = "#545454"
blue = "#569CD6"
cyan = "#56B6C2"
green = "#608B4E"
magenta = "#C678DD"
red = "#F44747"
white = "#D4D4D4"
yellow = "#DCDCAA"

