#!/bin/bash

# Install Brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# Install required tools
brew install docker
brew install fzf
brew install git
brew install helm
brew install jq
brew install minikube
brew install nvm
brew install neovim
brew install php
brew install ripgrep
brew install terraform
brew install tmux
brew install tree
brew install wget
brew install yarn
brew install z

# Install required apps if macos
if [[ $OSTYPE == 'darwin'* ]]; then
  brew install --cask alfred
  brew install --cask appcleaner
  brew install --cask bartender
  brew install --cask bettertouchtool
  brew install --cask discord
  brew install --cask docker
  brew install --cask google-chrome
  brew install --cask google-drive
  brew install --cask iterm2
  brew install --cask messenger
  brew install --cask numi
  brew install --cask obsidian
  brew install --cask rectangle
  brew install --cask slack
  brew install --cask spotify
  brew install --cask stats
  brew install --cask the-unarchiver
  brew install --cask ticktick
  brew install --cask topnotch
fi

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Install zsh plugins
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search

# Install Packer (Neovim)
git clone --depth 1 https://github.com/wbthomason/packer.nvim \
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# Symlink dotfiles
DOTFILES="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

rm -rf $HOME/.config/nvim
mkdir -p $HOME/.config/nvim
ln -s $DOTFILES/nvim/* $HOME/.config/nvim

rm -rf $HOME/.local/bin
mkdir -p $HOME/.local/bin
ln -s $DOTFILES/scripts/* $HOME/.local/bin

ln -sf $DOTFILES/zshrc $HOME/.zshrc
ln -sf $DOTFILES/p10k.zsh $HOME/.p10k.zsh
ln -sf $DOTFILES/aliases $HOME/.aliases
ln -sf $DOTFILES/tmux.conf $HOME/.tmux.conf
ln -sf $DOTFILES/vimrc $HOME/.vimrc
